SELECT ID FROM TICKET GROUP BY ID;

INSERT INTO TICKET(TICKET_NO, ID, TIME_CODE, PAY_COST, ORDER_DATE, TICKET_STATUS) VALUES (1, '', 1, 0, SYSDATE, 1);

SELECT * FROM TICKET WHERE ID = 'asurcombe1';

INSERT INTO BOOKED_SEAT(TICKET_NO, SEAT_CODE, SCREEN_NO)
VALUES (TICKET_SEQ.CURRVAL, ?, ?)


SELECT * FROM TICKET WHERE ID = 'asurcombe1';


SELECT BS.*, S.SCREEN_NAME
FROM TICKET            T
INNER JOIN BOOKED_SEAT BS
           ON T.TICKET_NO = BS.TICKET_NO
INNER JOIN SCREEN      S
           ON S.SCREEN_NO = BS.SCREEN_NO
WHERE TIME_CODE = 10;